#pragma once

#include <quark/api.h>
#include <quark/primitives.h>

enum QUARK_EXIT_CODE
{
    QUARK_EXIT_CODE_SUCCESS = 0,
    QUARK_EXIT_CODE_FAILED_TO_INITIALIZE_ENGINE = BIT(32 - 1),
    QUARK_EXIT_CODE_FAILED_TO_INITIALIZE_APPLICATION = BIT(32 - 2),
    QUARK_EXIT_CODE_FAILED_TO_CREATE_APPLICATION = BIT(32 - 3),
    QUARK_EXIT_CODE_FAILED_TO_RUN_APPLICATION = BIT(32 - 4),
    QUARK_EXIT_CODE_FAILED_TO_DESTROY_APPLICATION = BIT(32 - 5),
    QUARK_EXIT_CODE_FAILED_TO_SHUTDOWN_ENGINE = BIT(32 - 6),
};

QUARK_API QUARK_B8 init_quark(int argc, char** argv);
QUARK_API QUARK_B8 shutdown_quark(void);
